
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditrack-deployment
  namespace: meditrack-app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meditrack
  template:
    metadata:
      labels:
        app: meditrack
    spec:
      containers:
      - name: patient-record-service-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:patient-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: doctor-service-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:doctor-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: appointment-service-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:appointment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5007
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 5007
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 5007
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: notification-service-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:notification-service
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 6000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 6000
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: authentication-service-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:auth-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: agg-job-container
        image: 043309327322.dkr.ecr.us-east-1.amazonaws.com/meditrack_app:agg-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        envFrom:
        - configMapRef:
            name: meditrackapp-config
        - secretRef:
            name: meditrackapp-secrets
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 5006
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 5006
          initialDelaySeconds: 15
          periodSeconds: 20